-- Sin datos de arranque a proposito.
--
-- Las cifras de una persona no van en el repositorio: se cargan desde un
-- respaldo o se capturan en la app. Asi el codigo se puede publicar sin
-- exponer la situacion financiera de quien lo usa.
--
-- Para probar en local, insertar acreedores de ejemplo a mano.
