name: finanzas
description: "Gestor personal de deudas, gastos y plan de salida."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Bricolage
      fonts:
        - asset: assets/fuentes/Bricolage-600.ttf
          weight: 600
        - asset: assets/fuentes/Bricolage-700.ttf
          weight: 700
        - asset: assets/fuentes/Bricolage-800.ttf
          weight: 800
    - family: PublicSans
      fonts:
        - asset: assets/fuentes/PublicSans-400.ttf
          weight: 400
        - asset: assets/fuentes/PublicSans-500.ttf
          weight: 500
        - asset: assets/fuentes/PublicSans-600.ttf
          weight: 600
        - asset: assets/fuentes/PublicSans-700.ttf
          weight: 700
